name: Prisma
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api4.prismacloud.io
        with:
          api-key: ${{ secrets.PC_API_KEY }}
          soft_fail: true # optional: do not return an error code if there are failed checks
